version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork
      
  app:
    build: .
    container_name: app_container
    environment:
      DATABASE_URL: postgres://uabkjt577cjs7:p6d5f458b69dee6b5209ec341e3bebb93d345387c9f95946b8d401ec7a2d8ef6c@c8m0261h0c7idk.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com:5432/ddqm41aten05tj
    depends_on:
      - db
    ports:
      - "3001:3001"
    volumes:
      - .:/app
    networks:
      - mynetwork
    command: npm start

volumes:
  postgres_data:

networks:
  mynetwork: